---

- hosts: "tag_product_env_abinitio_*:&tag_function_devbox"
  become: yes
  vars_files:
    - vars/products.yml
  tasks:
   - name: Creating workdir for installation
     file:
       path: '/home/{{ ai_user }}/mhub'
       state: directory
       owner: '{{ ai_user }}'
       group: '{{ ai_grp }}'
       mode: 0755

   - name: Creating deployment dir
     file:
       path: '/home/{{ ai_user }}/mhub/deploy/config'
       state: directory
       owner: '{{ ai_user }}'
       group: '{{ ai_grp }}'
       mode: 0755

   - name: Creating mhub_local_root dir
     file:
       path: '{{ mhub_local_root }}'
       state: directory
       owner: '{{ ai_user }}'
       group: '{{ ai_grp }}'
       mode: 0755

   - name: Copy Mhub deploy_params.config file
     template:
       src: ./templates/deploy_params.config.j2
       dest: '/home/{{ ai_user }}/mhub/deploy/config/deploy_params.config'
       owner: '{{ ai_user }}'
       group: '{{ ai_grp }}'
       mode: 0755

   - name: File Package
     copy:
       src: '{{ file_path }}/{{ mhub_package }}'
       dest: '/home/{{ ai_user }}/mhub'
       owner: '{{ ai_user }}'
       group: '{{ ai_grp }}'
       mode: 0775

   - name: unarchiving the tar file
     unarchive:
       src: '/home/{{ ai_user }}/mhub/{{ mhub_package }}'
       dest: '/home/{{ ai_user }}/mhub'
       owner: '{{ ai_user }}'
       group: '{{ ai_grp }}'
       mode: 0775
       remote_src: yes

   - name: Creating Directory
     file:
       path: '/home/{{ ai_user }}/mhub/mh-install'
       state: present
       owner: '{{ ai_user }}'
       group: '{{ ai_grp }}'
       mode: 0775

   - name: Creating Directory
     file:
       path: '/home/{{ ai_user }}/mhub/mh-local-root'
       state: present
       owner: '{{ ai_user }}'
       group: '{{ ai_grp }}'
       mode: 0775

   - name: Installing MHUB and create war file
     ignore_errors: True
     become: yes
     become_user: '{{ ai_user }}'
     shell: |
        cd /home/{{ ai_user }}/mhub
        source /home/{{ ai_user }}/.profile
        pkg={{ mhub_package }}
        cd /home/{{ ai_user }}/mhub/`echo $pkg | awk -F ".tar" '{print $1}'`
        echo "n" | ./mh-install.ksh -install-root /home/{{ ai_user }}/mhub/mh-install
        export AB_MHUB_HOME=/home/{{ ai_user }}/mhub/mh-install/metadata-hub-3-3-6-1
        export AB_MHUB_LOCAL_ROOT={{ mhub_local_root }}
        mh-deploy -run -d /home/{{ ai_user }}/mhub/deploy