# Create partitions with parted module

- name: Create a new primary partition with a size of 1GB
  parted:
    device: /dev/nvme1n1
    label: gpt
    name: ab_work_dir_mount
    number: 1
    state: present
    part_start: 1GB
    part_end: 51GB
    part_type: primary


- name: Create a new extended partition with a size of 400GB
  parted:
    device: /dev/nvme1n1
    label: gpt
    name: serial_mount
    number: 2
    state: present
    part_start: 51GB
    part_end: 451GB
    part_type: extended


- name: Create a new extended partition with a size of 800GB
  parted:
    device: /dev/nvme1n1
    label: gpt
    name: mfs_part1_mount
    number: 3
    state: present
    part_start: 451GB
    part_end: 1251GB
    part_type: extended


- name: Create a new extended partition with a size of 800GB
  parted:
    device: /dev/nvme1n1
    label: gpt
    name: mfs_part2_mount
    number: 4
    state: present
    part_start: 1251GB
    part_end: 2051GB
    part_type: extended