# Mount the devices created with parted command

- name: Mount AB_WORK_DIR
  mount:
    path: /persist/abinitio
    src: /dev/nvme1n1p1
    fstype: ext4
    opts: defaults
    state: mounted



- name: Mount Serial,sandbox working area
  mount:
    path: /persist/serial
    src: /dev/nvme1n1p2
    fstype: ext4
    opts: defaults
    state: mounted


- name: Mount mfs data files part1
  mount:
    path: /persist/mfs_part1
    src: /dev/nvme1n1p3
    fstype: ext4
    opts: defaults
    state: mounted


- name: Mount mfs data files part2
  mount:
    path: /persist/mfs_part2
    src: /dev/nvme1n1p4
    fstype: ext4
    opts: defaults
    state: mounted
