---

- hosts: "tag_product_env_abinitio_*:&tag_function_runbox"
  strategy: debug
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - etchost
    - stdenv
    - databasedrivers
    - controlcenter
    - services