---

- hosts: "tag_product_env_abinitio_*:&tag_function_WFE"
  become: yes
  vars:
    tomcat_user: tomcat
    tomcat_install_dir: /opt/tomcat
    uusername: abiadm
    ugroup: abiadms

  tasks:
   - name: Create tomcat_user
     user:
       name: '{{ tomcat_user }}'
       shell: /bin/bash

   - name: Create abiadms group for admin from dev group to facilitate war file deploy
     group:
       name: '{{ ugroup }}'
       state: present

   - name: create abiadm user for deploying war files from dev node
     user:
       name: '{{ uusername }}'
       group: '{{ ugroup }}'
       shell: /bin/bash
       generate_ssh_key: yes
       ssh_key_file: .ssh/id_rsa

   - name: create installation Directory
     file:
       path: '{{ tomcat_install_dir }}'
       state: directory
       mode: 0755
       owner: '{{ tomcat_user }}'
       group: '{{ tomcat_user }}'

   - name: create working dir
     file:
       path: /home/'{{ tomcat_user }}'
       state: directory
       mode: 0755
       owner: '{{ tomcat_user }}'
       group: '{{ tomcat_user }}'

   - name: copying config files
     template:
       src: ./templates/tomcat.service.j2
       dest: /etc/systemd/system/tomcat.service

   - name: installing java
     yum:
       name: java-1.8.0-openjdk-devel
       state: present

   - name: installing java
     yum:
       name: wget
       state: present

   - name: Download tomcat
     get_url:
      url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.0.27/bin/apache-tomcat-8.0.27.tar.gz
      dest: /home/'{{ tomcat_user }}'
      mode: 0755
      owner: '{{ tomcat_user }}'
      group: '{{ tomcat_user }}'

   - name: Extract archive
     unarchive:
       src: /home/'{{ tomcat_user }}'/apache-tomcat-8.0.27.tar.gz
       dest: /opt/{{ tomcat_user }}
       extra_opts: [--strip-components=1]
       owner: '{{ tomcat_user }}'
       group: '{{ tomcat_user }}'
       mode: 0775
       remote_src: yes

   - name: start service tomcat
     systemd:
       state: started
       daemon_reload: yes
       name: tomcat
       enabled: yes

   - name: create authorized key file
     file:
       path: "/home/{{ uusername }}/.ssh/authorized_keys"
       state: touch
     become: yes
     become_user: '{{ uusername }}'

   - name: copy runhost pubkey to target user
     authorized_key:
       user: '{{ uusername }}'
       state: present
       key: "{{ lookup('file', './files/id_rsa.pub') }}"