# control center installation
---

- hosts: "tag_product_env_abinitio_*:&tag_function_devbox"
  become: yes
  vars_files:
    - vars/products.yml
    
  tasks:
   - name: copy Control>Center setup.properties
     template:
       src: ./templates/setup.properties.j2
       dest: '/home/{{ ai_user }}/setup.properties'
       owner: '{{ ai_user }}'
       group: '{{ ai_grp }}'
       mode: 0775

   - name: File copy
     copy:
       src: '{{ file_path }}/{{ cc_package }}'
       dest: '/home/{{ ai_user }}'
       owner: '{{ ai_user }}'
       group: '{{ ai_grp }}'
       mode: 0775

   - name: unarchiving the tar file
     unarchive:
       src: '/home/{{ ai_user }}/{{ cc_package }}'
       dest: '/home/{{ ai_user }}'
       owner: '{{ ai_user }}'
       group: '{{ ai_grp }}'
       mode: 0775
       remote_src: yes

   - name: Creating Directory
     file:
       path: '/home/{{ ai_user }}/cc-install'
       state: present
       owner: '{{ ai_user }}'
       group: '{{ ai_grp }}'
       mode: 0775

   - name: Creating Directory
     file:
       path: '/home/{{ ai_user }}/cc_root'
       state: present
       owner: '{{ ai_user }}'
       group: '{{ ai_grp }}'
       mode: 0775

   - name: setting up controlcenter
     become: yes
     become_user: '{{ ai_user }}'
     shell: |
        cd /home/{{ ai_user }}
        source /home/{{ ai_user }}/.profile
        pkg='{{ cc_package }}'
        export AB_CC_HOME=/home/{{ ai_user }}/cc-install/controlcenter-{{ cc_ver_num }}
        export AB_CC_LOCAL_ROOT=/home/{{ ai_user }}/cc_root
        cd /home/{{ ai_user }}/`echo $pkg | awk -F ".tar" '{print $1}'`
        ./cc-install.ksh -install-root /home/{{ ai_user }}/cc-install
        ${AB_CC_HOME}/bin/cc-admin create {{ deployment_name }} -from /home/{{ ai_user }}/setup.properties -batch true
        cd $AB_CC_LOCAL_ROOT/{{ deployment_name }}
        cp {{ deployment_name }}.war /tmp
        
   - name: Copying war files
     become: yes
     become_user: '{{ ai_user }}'
     shell: |
        scp /tmp/{{ deployment_name }}.war {{ web_user }}@{{ web_host }}:{{ CATALINA_HOME }}/webapps